<<: !include [shared/defaults.yaml, shared/standard.yaml]

constants:
  service: jellyfin

source_directories:
  - /mnt/source/jellyfin

exclude_patterns:
  - "sh:**/.aspnet/**"
  - "sh:**/.cache/**"
  - "sh:**/cache/**"
  - "sh:**/log/**"
