<<: !include [shared/defaults.yaml, shared/frequent.yaml]

constants:
  service: minecraft

source_directories:
  - /mnt/source/minecraft

exclude_patterns:
  - /mnt/source/minecraft/atm
  - /mnt/source/minecraft/manhunt
  - /mnt/source/minecraft/modded
  - /mnt/source/minecraft/nikhunt
  - "sh:**/.cache/**"
  - "sh:**/crash-reports/**"
  - "sh:**/logs/**"

repositories:
  - path: ${BORGBASE_MINECRAFT_REPO}
    label: "sagittarius-minecraft-borgbase"
