<<: !include [shared/defaults.yaml, shared/standard.yaml]

constants:
  service: nextcloud

source_directories:
  - /mnt/source/nextcloud

postgresql_databases:
  - name: nextcloud
    container: nextcloud-db
    port: 3306
    username: nextcloud
    password: ${NEXTCLOUD_DB_PASSWORD}

exclude_patterns:
  - /mnt/source/nextcloud/db
  - "**/log/"
  - "**/*.log"

repositories:
  - path: ${BORGBASE_NEXTCLOUD_REPO}
    label: "sagittarius-nextcloud-borgbase"
