<<: !include [shared/defaults.yaml, shared/standard.yaml, shared/database.yaml]

constants:
  service: nextcloud
  db_dump_cmd: "docker exec nextcloud-db mariadb-dump nextcloud"

source_directories:
  - /mnt/source/nextcloud

exclude_patterns:
  - /mnt/source/nextcloud/db
  - "sh:**/log/**"
  - "*.log"

repositories:
  - path: ${BORGBASE_NEXTCLOUD_REPO}
    label: "sagittarius-nextcloud-borgbase"
