name: qbittorrent

services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    networks:
      - gls
    environment:
      TZ: America/Toronto
      VPN_SERVICE_PROVIDER: mullvad
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY}
      WIREGUARD_ADDRESS: ${WIREGUARD_ADDRESS}
      SERVER_COUNTRIES: Canada
    # devices:
    #   - /dev/net/tun:/dev/net/tun
    restart: unless-stopped

  qbittorrent: # Set Options > Advanced > Network Interface to tun0 to prevent torrenting without VPN
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Toronto
      WEBUI_PORT: 8080
    volumes: # TODO: Move these to SSD to speed things up
      - /data/storage/qbittorrent/config:/config
      - /data/storage/qbittorrent/completed:/downloads
      - /data/storage/qbittorrent/incomplete:/incomplete
      - /data/storage/qbittorrent/torrents:/torrents
    stop_grace_period: "10s"
    restart: unless-stopped

networks:
  gls:
    external: true
