services:
  borgmatic:
    # Initialize with: docker exec borgmatic borgmatic init
    image: ghcr.io/borgmatic-collective/borgmatic:latest
    container_name: borgmatic # hostname same as container_name
    volumes:
      - ./config:/etc/borgmatic.d:ro
      - borg-ssh:/root/.ssh # Requires creating keys inside docker container shell (must have default name id_ed25519 to ensure it is detected without an ssh config
      - /data/storage:/mnt/source:ro
      - /data/backups/borg:/mnt/repos
      - borg-cache:/root/.cache/borg
      - borg-state:/root/.local/state/borgmatic
    environment:
      TZ: America/Toronto
      BORG_PASSPHRASE: ${BORG_PASSPHRASE}
      BORGBASE_NEXTCLOUD_REPO: ${BORGBASE_NEXTCLOUD_REPO}
      BORGBASE_MINECRAFT_REPO: ${BORGBASE_MINECRAFT_REPO}
      CRON: 0 3 * * *
    restart: unless-stopped
    stop_grace_period: 10m

volumes:
  borg-ssh:
  borg-cache:
  borg-state:
