#!/bin/env bash

# Run this script before starting the server

cd /storage/minecraft/atm

mkdir ./data

cp -r ./overrides/kubejs/* ./data/kubejs/
cp -r ./overrides/defaultconfigs/* ./data/defaultconfigs
