# Add exclude file for default exclusions maybe

exclude_caches: true

compression: auto,zstd
encryption_passphrase: ${BORG_PASSPHRASE}

archive_name_format: "sagittarius-{service}-{now:%Y-%m-%d-%H%M%S}"
# archive_name_format: "{hostname}-{service}"
# archive_hostname: sagittarius

repositories:
  - path: "/mnt/repos/sagittarius-{service}"
    label: "sagittarius-{service}-local"

retries: 5
retry_wait: 10

checks:
  - name: repository
    frequency: 1 week
  - name: data
    frequency: 1 month

check_last: 3
