name: immich

services:
  immich: # Port 2283
    image: ghcr.io/immich-app/immich-server:v3 # Or "latest"
    container_name: immich
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    env_file:
      - /storage/immich/.env
    environment:
      # DB_USERNAME: in env_file
      # DB_PASSWORD: in env_file
      # DB_DATABASE_NAME: in env_file

      TZ: America/Toronto
      CPU_CORES: 4
    volumes:
      - /storage/immich/library:/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - internal
      - gls
    restart: unless-stopped
    depends_on:
      - redis
      - database
    healthcheck:
      disable: false

  machine-learning: # Port 3003
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:v3
    container_name: immich-machine-learning
    # extends: # uncomment this section for hardware acceleration - see https://docs.immich.app/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - model-cache:/cache
    networks:
      - internal
    restart: unless-stopped

  redis:
    image: docker.io/valkey/valkey:9@sha256:8e8d64b405ce18f41b8e5ee20aa4687a8ed0022d1298f2ce31cdcf3a76e09411
    container_name: immich-redis
    networks:
      - internal
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping || exit 1

  database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    container_name: immich-postgres
    env_file:
      - /storage/immich/.env
    environment:
      # POSTGRES_USER: postgres
      # POSTGRES_PASSWORD: in env_file
      # POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: "--data-checksums"
      DB_STORAGE_TYPE: "HDD" # Required if database isn't stored on SSD
    volumes:
      - /storage/immich/postgres:/var/lib/postgresql/data
    shm_size: 128mb
    networks:
      - internal
    restart: unless-stopped

volumes:
  model-cache:

networks:
  internal:
  gls:
    external: true
