name: jellyfin

services:
  jellyfin: # Port 8096
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - /storage/jellyfin/config:/config
      - /storage/media:/media:ro
    networks:
      - gls
    tmpfs:
      - /cache:size=4G,mode=0755
    restart: unless-stopped

networks:
  gls:
    external: true
