name: servarr

services:
  radarr: # Port 7878
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    # depends_on:
    #   - prowlarr
    networks:
      - gls
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Toronto
    volumes:
      - /data/storage/radarr:/config
      - /data/storage/media/movies:/movies
      - /data/storage/qbittorrent/completed:/downloads
    restart: unless-stopped

  sonarr: # Port 8989
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - gls
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Toronto
    volumes:
      - /data/storage/sonarr:/config
      - /data/storage/media/tv:/tv
      - /data/storage/qbittorrent/completed:/downloads
    restart: unless-stopped

  lidarr: # Port 8686
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    networks:
      - gls
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Toronto
    volumes:
      - /data/storage/lidarr:/config
      - /data/storage/media/music:/music
      - /data/storage/qbittorrent/completed:/downloads
    restart: unless-stopped

  prowlarr: # Port 9696
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    # depends_on:
    #   - flaresolverr
    networks:
      # - prowlarr
      - gls
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Toronto
    volumes:
      - /data/storage/prowlarr:/config
    restart: unless-stopped
  
  # flaresolverr: # Port 8191
  #   image: flaresolverr/flaresolverr:latest
  #   container_name: flaresolverr
  #   networks:
  #     - prowlarr
  #   environment:
  #     # - LOG_LEVEL=${LOG_LEVEL:-info}
  #     TZ: America/Toronto
  #   restart: unless-stopped

networks:
  # prowlarr:
  gls:
    external: true
