services:
  server:
    image: itzg/minecraft-server:latest
    labels:
      mc-router.host: zodiac-timeline.gl.joinmc.link,zodiac-timeline.gl.at.ply.gg
    environment: # https://docker-minecraft-server.readthedocs.io/en/latest/variables/#rcon
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: "1.20.1"
      FORGE_VERSION: "latest"
      INIT_MEMORY: "4G"
      MAX_MEMORY: "8G"

      VIEW_DISTANCE: "12"
      SIMULATION_DISTANCE: "12"

      MOTD: "Sebastian's Modded Server"
      ENABLE_WHITELIST: "true"
      WHITELIST: "AwesomeFeet313,AKAPVP66,Ginormous_G,shubabidi,ultra_exdi,Mineor23"
      OPS: "AwesomeFeet313"
      EXISTING_WHITELIST_FILE: "MERGE"
      EXISTING_OPS_FILE: "MERGE"
      ALLOW_FLIGHT: "true" # For mods
    volumes:
      - ./data:/data
      - ./mods:/data/mods
    restart: no
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          memory: 9G
          cpus: '3'
    networks:
      - mc-net

networks:
  mc-net:
    external: true
