services:
  mc-router:
    image: itzg/mc-router:latest
    container_name: mc-router
    ports:
      - "48765:25565"
    command:
      - -debug
      - -in-docker
      - -auto-scale-up
      - -auto-scale-down
      - -auto-scale-down-after=5m
      - -auto-scale-allow-deny=/config/allow-deny.json
      - -auto-scale-asleep-motd=Server offline, join to initiate startup.
      - -auto-scale-loading-motd=Server starting, please wait.
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./allow-deny.json:/config/allow-deny.json:ro
    restart: unless-stopped
    networks:
      - mc-net

networks:
  mc-net:
    external: true
